# Generated by Django 4.2.30 on 2026-06-03 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDigest',
            fields=[
                ('date_id', models.DateField(primary_key=True, serialize=False, unique=True)),
                ('date_text', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=50)),
                ('tagline', models.CharField(default='नेति नेति — Less noise. More clarity.', max_length=255)),
                ('announcement', models.TextField(blank=True, null=True)),
                ('revise_summary', models.JSONField(blank=True, default=list)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='current_affairs_pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Daily Digest',
                'verbose_name_plural': 'Daily Digests',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('why_it_matters', models.TextField()),
                ('revise', models.TextField()),
                ('pyq_connect', models.TextField(blank=True, null=True)),
                ('digest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='current_affairs.dailydigest')),
            ],
        ),
        migrations.CreateModel(
            name='MCQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('options', models.JSONField(default=list)),
                ('answer', models.CharField(max_length=500)),
                ('explanation', models.TextField()),
                ('digest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcqs', to='current_affairs.dailydigest')),
            ],
        ),
        migrations.CreateModel(
            name='MainsQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('context', models.TextField()),
                ('digest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mains_questions', to='current_affairs.dailydigest')),
            ],
        ),
    ]
