# Generated by Django 4.2.30 on 2026-06-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('current_affairs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='revise',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='why_it_matters',
            field=models.TextField(blank=True),
        ),
    ]
