# Generated by Django 4.2.30 on 2026-07-07 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('current_affairs', '0002_alter_topic_revise_alter_topic_why_it_matters'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('total_questions', models.IntegerField()),
                ('answers_data', models.JSONField(blank=True, default=dict)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('digest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='current_affairs.dailydigest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_ca_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Quiz Attempt',
                'verbose_name_plural': 'Daily Quiz Attempts',
                'unique_together': {('user', 'digest')},
            },
        ),
    ]
