# Generated by Django 4.2.30 on 2026-06-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_free_test',
            field=models.BooleanField(default=False),
        ),
    ]
