# Generated by Django 4.2.30 on 2026-07-01 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_alter_quiz_options_quiz_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='source_image',
            field=models.FileField(blank=True, null=True, upload_to='source_covers/'),
        ),
    ]
