# Generated by Django 4.2.30 on 2026-07-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_book_source_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_current_affairs',
            field=models.BooleanField(default=False),
        ),
    ]
