# Generated by Django 4.2.30 on 2026-06-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_discount_applied_order_referral_code_used'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'Paid')), fields=('user', 'referral_code_used'), name='unique_paid_referral'),
        ),
    ]
