# Generated by Django 4.2.30 on 2026-06-16 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_unique_paid_referral'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='unique_paid_referral',
        ),
    ]
